remix.loadurl('https://github.com/OpenZeppelin/zeppelin-solidity/contracts/token/SafeERC20.sol')
remix.loadurl('https://github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC20.sol')
remix.loadurl('https://github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC20Capped.sol')
remix.loadurl('https://github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC20Mintable.sol')
remix.loadurl('https://github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC20Pausable.sol')
remix.loadurl('https://github.com/OpenZeppelin/zeppelin-solidity/contracts/token/IERC20.sol')